version: '3.8'

services:
  frontend:
    image: programie/financetracker
    command: frontend
    build: .
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      TZ: Europe/Berlin
      DATABASE_HOST: mysql
      DATABASE_NAME: finance_tracker
      DATABASE_USERNAME: finance_tracker
      DATABASE_PASSWORD: finance_tracker
  backend:
    image: programie/financetracker
    command: backend
    build: .
    links:
      - mysql
    environment:
      TZ: Europe/Berlin
      DATABASE_HOST: mysql
      DATABASE_NAME: finance_tracker
      DATABASE_USERNAME: finance_tracker
      DATABASE_PASSWORD: finance_tracker
  mysql:
    image: mariadb
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      TZ: Europe/Berlin
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: finance_tracker
      MYSQL_USER: finance_tracker
      MYSQL_PASSWORD: finance_tracker