version: '3.8'

services:
  frontend:
    image: programie/financetracker
    command: frontend
    build: .
    ports:
      - 80:80
    environment:
      DATABASE_HOST: my.db.host
      DATABASE_NAME: finance_tracker
      DATABASE_USERNAME: finance_tracker
      DATABASE_PASSWORD: "password-for-user"
  backend:
    image: programie/financetracker
    command: backend
    build: .
    ports:
      - 80:80
    environment:
      DATABASE_HOST: my.db.host
      DATABASE_NAME: finance_tracker
      DATABASE_USERNAME: finance_tracker
      DATABASE_PASSWORD: "password-for-user"
      SMTP_HOST: my.smtp.host
      SMTP_PORT: 587
      SMTP_USERNAME: my-smtp-user-name
      SMTP_PASSWORD: "password-for-user"
      MAIL_FROM: my-user@mail.host
      PUSHOVER_TOKEN: my-pushover-token